//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_Project_Mid.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        public Flat()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int FlatId { get; set; }
        public string FlatSize { get; set; }
        public string Location { get; set; }
        public string RoomDetails { get; set; }
        public string Rent { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual User User { get; set; }
    }
}
